### ISSUE TITLE
Test on EMR with a LARGE repository

### ISSUE THREAD

**Issue by arielshaqed** [treeverse/spark-client#17]

**Comment by johnnyaug** [comment]
Tested with a ~200M object repository, got nice parallelization on EMR:
Used clusters with 2, 5, and 20 worker nodes to perform a `du` operation on the objects. Got the following results:
2 nodes - 20 minutes
5 nodes - 6 minutes
20 nodes - 2 minutes.

The code to run this example can be found in the `examples` package of this repository.
